FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma/
RUN npm ci

COPY . .

RUN npx prisma generate

ENV NODE_ENV=production

CMD ["npm", "run", "worker"]
